stages:
  - build
  - scan

build-gradle-project:
  image: eclipse-temurin:17-jdk
  stage: build
  before_script:
    - chmod +x ./gradlew
  script:
    - ./gradlew build
  artifacts:
    reports:
      junit: '**/build/test-results/**/TEST-*.xml'

qodana-scan:
  image:
    name: jetbrains/qodana-jvm:$QODANA_VERSION
    entrypoint: [ "" ]
  stage: scan
  needs:
    - job: build-gradle-project
      artifacts: true
  cache:
    - key: qodana-$QODANA_VERSION-$CI_DEFAULT_BRANCH-$CI_COMMIT_REF_SLUG
      fallback_keys:
        - qodana-$QODANA_VERSION-$CI_DEFAULT_BRANCH-
        - qodana-$QODANA_VERSION-
      paths:
        - /tmp/.qodana/cache
  variables:
    QODANA_ENDPOINT: "https://qodana.cloud"
    QODANA_BRANCH: $CI_COMMIT_REF_NAME
    QODANA_VERSION: "2024.3"
  before_script:
    - chmod +x ./gradlew
    - ./gradlew generateKotlinSource
  script:
    - qodana --cache-dir=/tmp/.qodana/cache
